### ISSUE TITLE
Update base image to 2023.01 to include missing `file` command

### ISSUE THREAD

**Issue by MattFenelon** [CircleCI-Public/cimg-ruby#106]
The `file` command stopped being included in the image.

This is a continuation of https://github.com/CircleCI-Public/cimg-ruby/issues/103, which was accidentally closed because I added a `Fix:` tag to a PR in https://github.com/CircleCI-Public/cimg-base.

See the issue for details.

https://github.com/CircleCI-Public/cimg-base/pull/224 was recently merged in cimg-base, hopefully fixing the missing `file` command, in the base image.

Now we need this image to be updated to include that fix. Would it be possible to get the base image updated? I believe the image needs to be updated to `2023.01`.

Thank in advance.

**Comment by BytesGuy** [comment]
@MattFenelon The base image was updated in #110 : https://github.com/CircleCI-Public/cimg-ruby/pull/110/files

We build a new base image each month, however we only update the base image in the convenience images once per quarter. These updates are not retroactively applied to existing images, but will apply to new releases of the image after the change has been made - so in this case the 3.2.1 image was the next release after the bump in base image.

I hope this explanation helps! As this has now been merged in I will close this issue, but feel free to re-open it if you have any further concerns.
