### ISSUE TITLE
Ruby 3.2 with YJIT Enabled

### ISSUE THREAD

**Issue by gremerritt** [CircleCI-Public/cimg-ruby#108]
Are there plans to offer an image for an yjit-enabled ruby 3.2? Or to enable yjit on the standard 3.2 image?

**Comment by krzyczak** [comment]
Isn't it enough to either set `RUBY_YJIT_ENABLE=1` or `RUBYOPT="--yjit"`?

**Comment by gremerritt** [comment]
No, ruby needs to be compiled with support to enable the runtime setting:
```
circleci@c7c638735d36:~/project$ export RUBY_YJIT_ENABLE=1
circleci@c7c638735d36:~/project$ export RUBYOPT=1
circleci@c7c638735d36:~/project$ ruby --yjit --version
ruby: warning: Ruby was built without YJIT support. You may need to install rustc to build Ruby with YJIT.
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]
```

**Comment by gremerritt** [comment]
Perhaps poor phrasing in my initial report. I'm not suggesting the runtime setting be enabled by default, just that the ruby build support it.

**Comment by glaucocustodio** [comment]
I've migrated to https://github.com/docker-library/ruby, it already [supports YJIT](https://github.com/docker-library/ruby/pull/400/files)

**Comment by sebaherrera07** [comment]
I wonder if there are any plans to support YJIT in `cimg-ruby` soon?
