### ISSUE TITLE
Checkout error with ruby 3.2.1-browsers

### ISSUE THREAD

**Issue by kennyadsl** [CircleCI-Public/cimg-ruby#112]
Hello, we are facing issues with the new Ruby build released yesterday. 

Here's an example of the failure: 

https://app.circleci.com/pipelines/github/solidusio/solidus_starter_frontend/1841/workflows/2e2f78c2-56bd-4674-805d-536d299bf28c/jobs/6216

<details>
  <summary>Spin Up Environment Output</summary>

```
Starting container cimg/ruby:3.2-browsers
cimg/ruby:3.2-browsers:
  using image cimg/ruby@sha256:7d832a7af59cbff465edfbfe0ed05a29de4808c84ce5cf1f0f5e2de2b424b258
  pull stats: Image was already available so the image was not pulled
  time to create container: 10ms
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image is cached as cimg/ruby:3.2-browsers, but refreshing...
3.2-browsers: Pulling from cimg/ruby
Digest: sha256:7d832a7af59cbff465edfbfe0ed05a29de4808c84ce5cf1f0f5e2de2b424b258
Status: Image is up to date for cimg/ruby:3.2-browsers
Time to upload agent and config: 302.987646ms
Time to start containers: 328.100781ms
```
</details>

---

Here's another build using the same image, which succeeded instead:

https://app.circleci.com/pipelines/github/nebulab/solidus/843/workflows/4e61e6bb-ebfe-4cd5-9650-2047f4f20ec1/jobs/11697

<details>
  <summary>Spin Up Environment Output</summary>

```
Starting container cimg/ruby:3.2-browsers
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading cimg/ruby:3.2-browsers
3.2-browsers: Pulling from cimg/ruby
```
</details>

Can it be an issue with caching?

**Comment by waiting-for-dev** [comment]
It turns out our issue was related to https://github.com/CircleCI-Public/browser-tools-orb/pull/63. Bumping the version for the browser-tools orb fixed the checkout step. To be safe, we also moved our checkout step to the very first one. See https://github.com/solidusio/solidus_starter_frontend/pull/316.

**Comment by kennyadsl** [comment]
Thanks for reporting here @waiting-for-dev!
