### ISSUE TITLE
Feature Request: Ruby 3.3.0

### ISSUE THREAD

**Issue by guillaumebriday** [CircleCI-Public/cimg-ruby#149]
**Describe the Feature Request**
Add Ruby 3.3.0 to docker images

See: https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/

**Is your feature request related to a particular problem?**
No

**Comment by guillaumebriday** [comment]
Fix by https://github.com/CircleCI-Public/cimg-ruby/pull/150

**Comment by robcole** [comment]
Thanks for filing this and the PR @guillaumebriday! 

It'd be awesome to see support for this merged -- unfortunately it's blocking a production release of mine currently. 🤞

**Comment by JalexChen** [comment]
#153 Closes this
