### ISSUE TITLE
Feature Request: Ruby 3.3.1

### ISSUE THREAD

**Issue by kstevens715** [CircleCI-Public/cimg-ruby#165]
**Describe the Feature Request**
Add Ruby 3.3.1 to docker images

See: https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-3-1-released/

**Is your feature request related to a particular problem?**
For me it is. There's a bug in Ruby 3.3.0 that prevents me from being able to use it, but that should be fixed in 3.3.1:
* https://bugs.ruby-lang.org/issues/20085
* https://github.com/ruby-concurrency/concurrent-ruby/issues/1023

**Comment by ianterrell** [comment]
Obviously ditto with patch releases on 3.0, 3.1, and 3.2.

**Comment by jordan-brough** [comment]
Since these releases include security features it would be great to have updates soon if possible 🙏

**Comment by bermannoah** [comment]
Looks like there's an automated PR here: https://github.com/CircleCI-Public/cimg-ruby/pull/168, not sure who to ping to get it merged.

**Comment by joshhsoj1902** [comment]
I just merged #168 which addresses this. The new images are now available on dockerhub https://hub.docker.com/r/cimg/ruby/tags

**Comment by bermannoah** [comment]
Thank you @joshhsoj1902!
