### ISSUE TITLE
Add -browsers variants

### ISSUE THREAD

**Issue by swrobel** [CircleCI-Public/cimg-ruby#37]
Need these to run system tests that rely on headless Chrome/Firefox + Selenium

**Comment by r3dpointsp** [comment]
When can we expect the `-node-browsers` variants? It's blocking my transition from legacy images to the new images. Right now I've only been able to upgrade my standalone yarn builds to the newer node images. My ruby, ruby+react, and cypress builds are stuck on the old images.

**Comment by felicianotech** [comment]
We have a beta going: https://discuss.circleci.com/t/next-gen-convenience-image-browsers-variant-beta/37794?u=felicianotech

**Comment by swrobel** [comment]
@felicianotech these don't seem to be available: https://hub.docker.com/r/cimg/ruby/tags?page=1&name=browsers

**Comment by felicianotech** [comment]
Checking

**Comment by felicianotech** [comment]
@swrobel Fixed

**Comment by swrobel** [comment]
Still needs node-browsers variants...

**Comment by felicianotech** [comment]
Please read the CircleCI Discuss post I linked, it explains how the variant tags have and have not changed: https://github.com/CircleCI-Public/cimg-ruby/issues/37#issuecomment-712332747

**Comment by felicianotech** [comment]
This has been completed.
