### ISSUE TITLE
I have to install libmysqlclient-dev

### ISSUE THREAD

**Issue by kevinluo201** [CircleCI-Public/cimg-ruby#45]
I have to install libmysqlclient-dev to install mysql2 gem
- run: sudo apt-get update -qq && sudo apt-get install -y build-essential libmysqlclient-dev

and I didn't need this in circleci's ruby image

or is there any better solution?

**Comment by felicianotech** [comment]
Which image tag are you using?

**Comment by kevinluo201** [comment]
`cimg/ruby:2.6.5-node`
Sorry, I didn't mentioned this.
I thought because only MySQL/MariaSQL users need this libmysqlclient-dev, cimg choose to  move out that because of unnecessary?

**Comment by felicianotech** [comment]
Hi @kevinluo201,

I know it's been awhile, sorry about that. After you opened this Issue we did take a look at the image and implemented something.

Starting with the Ruby v2.6.6 image, `libmariadb-dev` is pre-installed. This is an alternative package to the one you mentioned. This means that `gem install mysql2` will work out of the box starting from that image. I hope that helps.

**Comment by kevinluo201** [comment]
@felicianotech thanks 🙏
