### ISSUE TITLE
pkg-config is not installed.

### ISSUE THREAD

**Issue by r-plus** [CircleCI-Public/cimg-ruby#55]
Hello.

Today I try to migrate to this new generation image `cimg/ruby:2.5.8-browsers` from `circleci/ruby:2.5.8-node-browsers` then encountered `rmagick` native extension build error while `bundle install`.
Error log describe `pkg-config` is not installed.

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/circleci/****-server/vendor/bundle/ruby/2.5.0/gems/rmagick-2.16.0/ext/RMagick
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.5.0 -r
./siteconf20201111-3277-iz0yzn.rb extconf.rb
checking for gcc... yes
checking for Magick-config... no
checking for pkg-config... no
Can't install RMagick 2.16.0. Can't find Magick-config or pkg-config in
/home/circleci/.rubygems/bin:/gems/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

yes i know, adding `sudo apt-get install pkg-config` step will resolve this error.

This issue is just for question:
"`pkg-config` package is optional for this docker image, is this intended?"

**Comment by felicianotech** [comment]
Looking into this.

**Comment by felicianotech** [comment]
The package `pkg-config` will be installed in the upstream Ubuntu image, CircleCI Base (`cimg-base`). This will be published in December. The first Ruby versions to be published after December 1st, 2020 will get this update.

In the meantime, if you are to use a current image, I would do what you suggested and run `sudo apt-get install pkg-config` in your CircleCI config.

Thank you for the issue.

**Comment by r-plus** [comment]
thanks for update.
